# Generated by Django 6.0.6 on 2026-06-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(help_text='Contoh: K1, K2', max_length=10)),
                ('nama', models.CharField(help_text='Contoh: Visi, Misi, Tujuan, dan Strategi', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'LED - Kriteria',
            },
        ),
        migrations.CreateModel(
            name='LedKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: C.1.4', max_length=20)),
                ('deskripsi', models.TextField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponen', to='dokumen.kriteria')),
            ],
            options={
                'verbose_name_plural': 'LED - Komponen',
            },
        ),
        migrations.CreateModel(
            name='LkpsElemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel_referensi', models.CharField(help_text='Contoh: Tabel 2.a, Tabel 3.a.1', max_length=50)),
                ('deskripsi', models.TextField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemen', to='dokumen.kriteria')),
            ],
            options={
                'verbose_name_plural': 'LKPS - Elemen',
            },
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('kebijakan', 'Kebijakan'), ('bukti_kegiatan', 'Bukti Kegiatan'), ('laporan', 'Laporan'), ('instrumen', 'Instrumen'), ('monev', 'Monev'), ('lainnya', 'Lainnya')], max_length=30)),
                ('deskripsi', models.TextField()),
                ('link_gdrive', models.URLField(help_text='Masukkan URL Google Drive dokumen', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dipakai_led', models.ManyToManyField(blank=True, related_name='dokumen_terkait', to='dokumen.ledkomponen')),
                ('dipakai_lkps', models.ManyToManyField(blank=True, related_name='dokumen_terkait', to='dokumen.lkpselemen')),
            ],
            options={
                'verbose_name_plural': 'Arsip Dokumen',
                'ordering': ['-created_at'],
            },
        ),
    ]
