# Generated by Django 6.0.6 on 2026-06-26 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='dipakai_lkps',
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='dipakai_led',
            field=models.ManyToManyField(blank=True, related_name='dokumen_led_terkait', to='dokumen.ledkomponen'),
        ),
        migrations.CreateModel(
            name='DokumenLkps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, help_text='Catatan tambahan relasi', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lkps_elemen', to='dokumen.dokumen')),
                ('lkps_elemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_terkait', to='dokumen.lkpselemen')),
            ],
            options={
                'verbose_name_plural': 'Dokumen - LKPS Elemen',
                'ordering': ['dokumen', 'lkps_elemen'],
                'unique_together': {('dokumen', 'lkps_elemen')},
            },
        ),
    ]
